# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: product.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'product.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rproduct.proto\x12\x07product\"$\n\x0eProductRequest\x12\x12\n\nproduct_id\x18\x01 \x01(\t\"C\n\x12ProductListRequest\x12\x0c\n\x04page\x18\x01 \x01(\x05\x12\r\n\x05limit\x18\x02 \x01(\x05\x12\x10\n\x08\x63\x61tegory\x18\x03 \x01(\t\"|\n\x14\x43reateProductRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\r\n\x05price\x18\x03 \x01(\x01\x12\r\n\x05stock\x18\x04 \x01(\x05\x12\x10\n\x08\x63\x61tegory\x18\x05 \x01(\t\x12\x11\n\timage_url\x18\x06 \x01(\t\"\x90\x01\n\x14UpdateProductRequest\x12\x12\n\nproduct_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\r\n\x05price\x18\x04 \x01(\x01\x12\r\n\x05stock\x18\x05 \x01(\x05\x12\x10\n\x08\x63\x61tegory\x18\x06 \x01(\t\x12\x11\n\timage_url\x18\x07 \x01(\t\"\xac\x01\n\x0fProductResponse\x12\x12\n\nproduct_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\r\n\x05price\x18\x04 \x01(\x01\x12\r\n\x05stock\x18\x05 \x01(\x05\x12\x10\n\x08\x63\x61tegory\x18\x06 \x01(\t\x12\x11\n\timage_url\x18\x07 \x01(\t\x12\x0e\n\x06status\x18\x08 \x01(\t\x12\x0f\n\x07message\x18\t \x01(\t\"m\n\x13ProductListResponse\x12*\n\x08products\x18\x01 \x03(\x0b\x32\x18.product.ProductResponse\x12\r\n\x05total\x18\x02 \x01(\x05\x12\x0c\n\x04page\x18\x03 \x01(\x05\x12\r\n\x05limit\x18\x04 \x01(\x05\x32\xb0\x02\n\x0eProductService\x12?\n\nGetProduct\x12\x17.product.ProductRequest\x1a\x18.product.ProductResponse\x12I\n\x0cListProducts\x12\x1b.product.ProductListRequest\x1a\x1c.product.ProductListResponse\x12H\n\rCreateProduct\x12\x1d.product.CreateProductRequest\x1a\x18.product.ProductResponse\x12H\n\rUpdateProduct\x12\x1d.product.UpdateProductRequest\x1a\x18.product.ProductResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'product_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PRODUCTREQUEST']._serialized_start=26
  _globals['_PRODUCTREQUEST']._serialized_end=62
  _globals['_PRODUCTLISTREQUEST']._serialized_start=64
  _globals['_PRODUCTLISTREQUEST']._serialized_end=131
  _globals['_CREATEPRODUCTREQUEST']._serialized_start=133
  _globals['_CREATEPRODUCTREQUEST']._serialized_end=257
  _globals['_UPDATEPRODUCTREQUEST']._serialized_start=260
  _globals['_UPDATEPRODUCTREQUEST']._serialized_end=404
  _globals['_PRODUCTRESPONSE']._serialized_start=407
  _globals['_PRODUCTRESPONSE']._serialized_end=579
  _globals['_PRODUCTLISTRESPONSE']._serialized_start=581
  _globals['_PRODUCTLISTRESPONSE']._serialized_end=690
  _globals['_PRODUCTSERVICE']._serialized_start=693
  _globals['_PRODUCTSERVICE']._serialized_end=997
# @@protoc_insertion_point(module_scope)
