version: '3.8'

services:
  user_service:
    build: ./user_service
    ports:
      - "50051:50051"
    environment:
      - DB_HOST=postgres-user
      - DB_PORT=5432
    depends_on:
      - postgres-user

  product_service:
    build: ./product_service
    ports:
      - "50052:50052"
    environment:
      - DB_HOST=postgres-product
      - DB_PORT=5432
    depends_on:
      - postgres-product

  order_service:
    build: ./order_service
    ports:
      - "50054:50054"
    environment:
      - DB_HOST=postgres-order
      - DB_PORT=5432
    depends_on:
      - postgres-order

  cart_service:
    build: ./cart_service
    ports:
      - "50053:50053"
    environment:
      - DB_HOST=postgres-tracking
      - DB_PORT=5432
    depends_on:
      - postgres-tracking

  api-gateway:
    build: ./api_gateway
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=postgres-admin
      - DB_PORT=5432
    depends_on:
      - postgres-admin

  # Databases for each service
  postgres-user:
    image: postgres:13
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  postgres-product:
    image: postgres:13
    environment:
      POSTGRES_DB: productdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"

  postgres-order:
    image: postgres:13
    environment:
      POSTGRES_DB: orderdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"

  postgres-tracking:
    image: postgres:13
    environment:
      POSTGRES_DB: trackingdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5435:5432"

  postgres-admin:
    image: postgres:13
    environment:
      POSTGRES_DB: admindb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5436:5432"
