# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: payment.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'payment.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rpayment.proto\x12\x07payment\"\x92\x01\n\x0ePaymentRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x01\x12\x16\n\x0epayment_method\x18\x04 \x01(\t\x12\x13\n\x0b\x63\x61rd_number\x18\x05 \x01(\t\x12\x13\n\x0b\x65xpiry_date\x18\x06 \x01(\t\x12\x0b\n\x03\x63vv\x18\x07 \x01(\t\"+\n\x15PaymentDetailsRequest\x12\x12\n\npayment_id\x18\x01 \x01(\t\"\xa9\x01\n\x0fPaymentResponse\x12\x12\n\npayment_id\x18\x01 \x01(\t\x12\x10\n\x08order_id\x18\x02 \x01(\t\x12\x0f\n\x07user_id\x18\x03 \x01(\t\x12\x0e\n\x06\x61mount\x18\x04 \x01(\x01\x12\x0e\n\x06status\x18\x05 \x01(\t\x12\x16\n\x0epayment_method\x18\x06 \x01(\t\x12\x16\n\x0etransaction_id\x18\x07 \x01(\t\x12\x0f\n\x07message\x18\x08 \x01(\t2\x9d\x01\n\x0ePaymentService\x12\x43\n\x0eProcessPayment\x12\x17.payment.PaymentRequest\x1a\x18.payment.PaymentResponse\x12\x46\n\nGetPayment\x12\x1e.payment.PaymentDetailsRequest\x1a\x18.payment.PaymentResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'payment_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PAYMENTREQUEST']._serialized_start=27
  _globals['_PAYMENTREQUEST']._serialized_end=173
  _globals['_PAYMENTDETAILSREQUEST']._serialized_start=175
  _globals['_PAYMENTDETAILSREQUEST']._serialized_end=218
  _globals['_PAYMENTRESPONSE']._serialized_start=221
  _globals['_PAYMENTRESPONSE']._serialized_end=390
  _globals['_PAYMENTSERVICE']._serialized_start=393
  _globals['_PAYMENTSERVICE']._serialized_end=550
# @@protoc_insertion_point(module_scope)
