FROM python:3.9-slim

WORKDIR /order_service

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY . .
RUN python -m grpc_tools.protoc -I../proto --python_out=. --grpc_python_out=. ../proto/order_service.proto ../proto/common.proto

EXPOSE 50054

CMD ["python", "service.py"]
