FROM python:3.9-slim

WORKDIR /admin_service

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY . .
RUN python -m grpc_tools.protoc -I../protos --python_out=. --grpc_python_out=. ../protos/admin_service.proto ../protos/common.proto


CMD ["python", "service.py"]
