#version: '3.8'

services:
  user_service:
    build: ./user_service
    ports:
      - "50051:50051"
    networks:
      - ecommerce_network

  product_service:
    build: ./product_service
    ports:
      - "50052:50052"
    networks:
      - ecommerce_network

  order_service:
    build: ./order_service
    ports:
      - "50053:50053"
    networks:
      - ecommerce_network
    depends_on:
      - user_service
      - product_service

  payment_service:
    build: ./payment_service
    ports:
      - "50054:50054"
    networks:
      - ecommerce_network

  shipping_service:
    build: ./shipping_service
    ports:
      - "50055:50055"
    networks:
      - ecommerce_network

  client:
    build: ./client
    networks:
      - ecommerce_network
    depends_on:
      - user_service
      - product_service
      - order_service
      - payment_service
      - shipping_service
    stdin_open: true
    tty: true

networks:
  ecommerce_network:
    driver: bridge
