# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import shipping_pb2 as shipping__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in shipping_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ShippingServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateShipping = channel.unary_unary(
                '/shipping.ShippingService/CreateShipping',
                request_serializer=shipping__pb2.ShippingRequest.SerializeToString,
                response_deserializer=shipping__pb2.ShippingResponse.FromString,
                _registered_method=True)
        self.GetShipping = channel.unary_unary(
                '/shipping.ShippingService/GetShipping',
                request_serializer=shipping__pb2.ShippingDetailsRequest.SerializeToString,
                response_deserializer=shipping__pb2.ShippingResponse.FromString,
                _registered_method=True)
        self.UpdateShippingStatus = channel.unary_unary(
                '/shipping.ShippingService/UpdateShippingStatus',
                request_serializer=shipping__pb2.UpdateShippingStatusRequest.SerializeToString,
                response_deserializer=shipping__pb2.ShippingResponse.FromString,
                _registered_method=True)


class ShippingServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateShipping(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetShipping(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateShippingStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ShippingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateShipping': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateShipping,
                    request_deserializer=shipping__pb2.ShippingRequest.FromString,
                    response_serializer=shipping__pb2.ShippingResponse.SerializeToString,
            ),
            'GetShipping': grpc.unary_unary_rpc_method_handler(
                    servicer.GetShipping,
                    request_deserializer=shipping__pb2.ShippingDetailsRequest.FromString,
                    response_serializer=shipping__pb2.ShippingResponse.SerializeToString,
            ),
            'UpdateShippingStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateShippingStatus,
                    request_deserializer=shipping__pb2.UpdateShippingStatusRequest.FromString,
                    response_serializer=shipping__pb2.ShippingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'shipping.ShippingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('shipping.ShippingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ShippingService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateShipping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shipping.ShippingService/CreateShipping',
            shipping__pb2.ShippingRequest.SerializeToString,
            shipping__pb2.ShippingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetShipping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shipping.ShippingService/GetShipping',
            shipping__pb2.ShippingDetailsRequest.SerializeToString,
            shipping__pb2.ShippingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateShippingStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shipping.ShippingService/UpdateShippingStatus',
            shipping__pb2.UpdateShippingStatusRequest.SerializeToString,
            shipping__pb2.ShippingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
